### ISSUE TITLE
Failing test in Drupal 10 : PHP Fatal error:  Uncaught AssertionError: assert(count($nodes) === 1) 

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov_subsites#140]
Coming from https://github.com/localgovdrupal/localgov_subsites/actions/runs/7478901653/job/20526906879?pr=138#step:5:11
```
Run mkdir -p ./html/web/sites/simpletest && chmod 777 ./html/web/sites/simpletest
ParaTest v6.11.0 upon PHPUnit 9.6.15 by Sebastian Bergmann and contributors.

PHP Fatal error:  Uncaught AssertionError: assert(count($nodes) === 1) in /var/www/html/vendor/brianium/paratest/src/Logging/JUnit/TestCase.php:79
Stack trace:
#0 /var/www/html/vendor/brianium/paratest/src/Logging/JUnit/TestCase.php(79): assert(false, 'assert(count($n...')
#1 /var/www/html/vendor/brianium/paratest/src/Logging/JUnit/TestCase.php(95): ParaTest\Logging\JUnit\TestCase::ParaTest\Logging\JUnit\{closure}(Array)
#2 /var/www/html/vendor/brianium/paratest/src/Logging/JUnit/Reader.php(71): ParaTest\Logging\JUnit\TestCase::caseFromNode(Object(SimpleXMLElement))
#3 /var/www/html/vendor/brianium/paratest/src/Logging/JUnit/Reader.php(58): ParaTest\Logging\JUnit\Reader->parseTestSuite(Object(SimpleXMLElement), false)
#4 /var/www/html/vendor/brianium/paratest/src/Logging/JUnit/Reader.php(49): ParaTest\Logging\JUnit\Reader->parseTestSuite(Object(SimpleXMLElement), true)
#5 /var/www/html/vendor/brianium/paratest/src/Runners/PHPUnit/ResultPrinter.php(273): ParaTest\Logging\JUnit\Reader->__construct('/tmp/PT_pJn1Vw')
#6 /var/www/html/vendor/brianium/paratest/src/Runners/PHPUnit/Runner.php([10](https://github.com/localgovdrupal/localgov_subsites/actions/runs/7478901653/job/20526906879?pr=138#step:5:11)8): ParaTest\Runners\PHPUnit\ResultPrinter->printFeedback(Object(ParaTest\Runners\PHPUnit\Suite))
#7 /var/www/html/vendor/brianium/paratest/src/Runners/PHPUnit/Runner.php(41): ParaTest\Runners\PHPUnit\Runner->testIsStillRunning(Object(ParaTest\Runners\PHPUnit\Worker\RunnerWorker))
#8 /var/www/html/vendor/brianium/paratest/src/Runners/PHPUnit/BaseRunner.php(80): ParaTest\Runners\PHPUnit\Runner->doRun()
#9 /var/www/html/vendor/brianium/paratest/src/Console/Commands/ParaTestCommand.php(102): ParaTest\Runners\PHPUnit\BaseRunner->run()
#10 /var/www/html/vendor/symfony/console/Command/Command.php(326): ParaTest\Console\Commands\ParaTestCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#[11](https://github.com/localgovdrupal/localgov_subsites/actions/runs/7478901653/job/20526906879?pr=138#step:5:12) /var/www/html/vendor/symfony/console/Application.php(1078): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#[12](https://github.com/localgovdrupal/localgov_subsites/actions/runs/7478901653/job/20526906879?pr=138#step:5:13) /var/www/html/vendor/symfony/console/Application.php(324): Symfony\Component\Console\Application->doRunCommand(Object(ParaTest\Console\Commands\ParaTestCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#[13](https://github.com/localgovdrupal/localgov_subsites/actions/runs/7478901653/job/20526906879?pr=138#step:5:14) /var/www/html/vendor/symfony/console/Application.php(175): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 /var/www/html/vendor/brianium/paratest/bin/paratest(37): Symfony\Component\Console\Application->run()
#15 /var/www/html/bin/paratest(119): include('/var/www/html/v...')
#16 {main}
  thrown in /var/www/html/vendor/brianium/paratest/src/Logging/JUnit/TestCase.php on line 79

Fatal error: Uncaught AssertionError: assert(count($nodes) === 1) in /var/www/html/vendor/brianium/paratest/src/Logging/JUnit/TestCase.php:79
Stack trace:
#0 /var/www/html/vendor/brianium/paratest/src/Logging/JUnit/TestCase.php(79): assert(false, 'assert(count($n...')
#1 /var/www/html/vendor/brianium/paratest/src/Logging/JUnit/TestCase.php(95): ParaTest\Logging\JUnit\TestCase::ParaTest\Logging\JUnit\{closure}(Array)
#2 /var/www/html/vendor/brianium/paratest/src/Logging/JUnit/Reader.php(71): ParaTest\Logging\JUnit\TestCase::caseFromNode(Object(SimpleXMLElement))
#3 /var/www/html/vendor/brianium/paratest/src/Logging/JUnit/Reader.php(58): ParaTest\Logging\JUnit\Reader->parseTestSuite(Object(SimpleXMLElement), false)
#4 /var/www/html/vendor/brianium/paratest/src/Logging/JUnit/Reader.php(49): ParaTest\Logging\JUnit\Reader->parseTestSuite(Object(SimpleXMLElement), true)
#5 /var/www/html/vendor/brianium/paratest/src/Runners/PHPUnit/ResultPrinter.php(273): ParaTest\Logging\JUnit\Reader->__construct('/tmp/PT_pJn1Vw')
#6 /var/www/html/vendor/brianium/paratest/src/Runners/PHPUnit/Runner.php(108): ParaTest\Runners\PHPUnit\ResultPrinter->printFeedback(Object(ParaTest\Runners\PHPUnit\Suite))
#7 /var/www/html/vendor/brianium/paratest/src/Runners/PHPUnit/Runner.php(41): ParaTest\Runners\PHPUnit\Runner->testIsStillRunning(Object(ParaTest\Runners\PHPUnit\Worker\RunnerWorker))
#8 /var/www/html/vendor/brianium/paratest/src/Runners/PHPUnit/BaseRunner.php(80): ParaTest\Runners\PHPUnit\Runner->doRun()
#9 /var/www/html/vendor/brianium/paratest/src/Console/Commands/ParaTestCommand.php(102): ParaTest\Runners\PHPUnit\BaseRunner->run()
#10 /var/www/html/vendor/symfony/console/Command/Command.php(326): ParaTest\Console\Commands\ParaTestCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 /var/www/html/vendor/symfony/console/Application.php(1078): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 /var/www/html/vendor/symfony/console/Application.php(324): Symfony\Component\Console\Application->doRunCommand(Object(ParaTest\Console\Commands\ParaTestCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 /var/www/html/vendor/symfony/console/Application.php(175): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#[14](https://github.com/localgovdrupal/localgov_subsites/actions/runs/7478901653/job/20526906879?pr=138#step:5:15) /var/www/html/vendor/brianium/paratest/bin/paratest(37): Symfony\Component\Console\Application->run()
#[15](https://github.com/localgovdrupal/localgov_subsites/actions/runs/7478901653/job/20526906879?pr=138#step:5:16) /var/www/html/bin/paratest(119): include('/var/www/html/v...')
#[16](https://github.com/localgovdrupal/localgov_subsites/actions/runs/7478901653/job/20526906879?pr=138#step:5:17) {main}
  thrown in /var/www/html/vendor/brianium/paratest/src/Logging/JUnit/TestCase.php on line 79
Error: Process completed with exit code [25](https://github.com/localgovdrupal/localgov_subsites/actions/runs/7478901653/job/20526906879?pr=138#step:5:26)5.

**Comment by markconroy** [comment]
@finnlewis I'm going to close this issue since the corresponding PR was merged and released. 

Please re-open if you think this still needs work.
